trigger:
    branches:
        include:
            - main
            - feature/*

variables:
    - group: 'aks-nonprod'

stages:
    - stage: Terraform
      displayName: 'Terraform Pipeline'
      jobs:
          - job: CustomContainer
            displayName: 'Run commands in custom container'
            pool:
                vmImage: 'ubuntu-latest'
            container:
                image: ballastacr.azurecr.io/terraform:1.0.0
                endpoint: ballastacr
                options: '-w $(Build.SourcesDirectory)/2.0_non_prod'
            steps:
                - checkout: self
                  persistCredentials: true
                  clean: true

                - task: CmdLine@2
                  displayName: 'Az Authentication'
                  inputs:
                      script: |
                          az login --service-principal --username $(TF_VAR_client_id) --password $(TF_VAR_client_secret) --tenant $(TF_VAR_tenant_id)

                - task: CmdLine@2
                  displayName: 'Terraform init'
                  inputs:
                      script: |
                          terraform init

                - task: CmdLine@2
                  displayName: 'Terraform validate'
                  inputs:
                      script: |
                          terraform validate

                - task: CmdLine@2
                  displayName: 'Terraform plan'
                  inputs:
                      script: |
                          terraform plan -out=tfplan

                - task: CmdLine@2
                  displayName: 'Terraform apply'
                  inputs:
                      script: |
                          terraform apply tfplan
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
